[project]
name = "auto-course-selector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "pycryptodome>=3.23.0",
    "requests>=2.32.4",
    "selenium>=4.33.0",
]
