# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins

def approx_chebyshev_rust(x:builtins.float) -> builtins.float:
    r"""
    Fast Chebyshev approximation of sin(x) using 2-step recurrence formula.
    Works for x in [-pi/2, pi/2].
    """
    ...

def approx_legendre_rust(x:builtins.float) -> builtins.float:
    r"""
    Approximates sin(x) using Legendre polynomial with Horner's method.
    Works for x in [-pi/2, pi/2].
    """
    ...

