def approx_chebyshev_cy(x) -> 'double':
    """approx_chebyshev_cy(double x) -> double

    Fast Chebyshev approximation of sin(x) for x in [-pi/2, pi/2].
    """

def approx_legendre_cy(x) -> 'double':
    """approx_legendre_cy(double x) -> double

    Fast approximation of sin(x) for x in [-pi/2, pi/2].
    """

def approx_legendre_cy_3ord(x) -> 'double':
    """approx_legendre_cy_3ord(double x) -> double

    Fast 3rd order Legendre approximation of sin(x) for x in [-pi/2, pi/2].
    """

def approx_lut_cy(x):
    """approx_lut_cy(double x)

    Lookup table with linear interpolation (1024 entries).
    """

def init_lut():
    """Initialize lookup tables (called from Python)."""


# This file was generated by stubgen-pyx v0.1.4