# Build a specific target (cython, rust, etc.)
build target:
    @echo "Building {{ target }}"
    @just build-{{ target }}

# Cython build recipe
build-cython:
    uv run python setup.py build_ext --inplace
    # maturin automatically places the built .so files in src/

    @cp src/approx_cy*.so .
build-rust:
    maturin build --release

benchmark:
    uv run python benchmark.py

setup:
    @echo "Setting up the environment"
    uv sync
    source ./.venv/bin/activate
    just build cython
    just build rust
run: setup
    just benchmark